[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.variants.design]
capital-e = "serifed"
capital-i = "serifed"
capital-l = "serifed"
capital-q = "crossing"
capital-s = "bilateral-inward-serifed"
capital-t = "serifed"
i = "zshaped"
l = "zshaped"
k = "symmetric-connected-serifed"
m = "short-leg"
n = "straight"
p = "motion-serifed"
q = "straight-motion-serifed"
r = "serifed"
v = "curly-motion-serifed"
zero = "long-dotted"
asterisk = "flip-penta-low"
at = "short"
percent = "rings-continuous-slash"
